name: ambev_track
description: Ferramenta de “tracking”.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  asuka: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  dio: ^4.0.4
  duration_picker: ^1.1.0+1
  easy_mask: ^2.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_modular: ^4.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  internet_connection_checker: ^0.0.1+3

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  modular_test: ^1.0.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf
